### PR TITLE
Stepped Rings Method - Fix camera angle

### PR DESCRIPTION
**Pull request by acbuynak**
Following the resolution of Issue #2, the changes should be integrated into the main code set.
This branch will need updated before merging, but creating PR to start merge discussion.

I see two potential routes of merging:
* rebasing all commits onto master
* smash & rebase all commits onto master
* new clean commit which applies ONLY the corrected fixes with a reference back to the issue and debug-branch history.

### CODE REVIEW

**Comment by Schellenberg3** [comment]
List of changes to incorporate once these branches are merged: 

* Move `_rotMatrix_newTechnique()` our of the stepped rings class and in to its own function,
* Move the code that creates a ring to `shapes.py` so other paths (e.g. a dome) can call it to get a circle of arbitrary radius or size
* Re-write `InclinedPlanes` class to construct relative to the robot and to take advantage of the rotation matrix
* Make sure that `SteppedRings` formats messages properly 
  * maybe just make a function to take a list of poses to do this (is this what `tranformations.py` is intended for?)

**Review by Schellenberg3 — COMMENTED** [review]
I do think these look good.  

Is `debug_pose_angle.py` something we'd like to include in the main files? Not sure exactly what its purpose is.

**Comment by acbuynak** [comment]
Agreed on 'debug_pose_angle.py'.
It could be a useful visualization tool. But really only supports the generation of the rotation matrix.

**Comment by acbuynak** [comment]
Preparing a squash merge for this fix as many of the commits were development and not notable. 
The changes made there are documented here and in the original issue.

**Pull request merged**
